# Ditulis Jenkins dari deploy/ repo timesheet; jangan diubah tangan.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worklog-dev
resources:
  - timesheet.yaml
images:
  - name: app
    newName: 127.0.0.1:5000/worklog/timesheet
    newTag: "8d74e99"
