# Ditulis Jenkins dari deploy/ repo template; jangan diubah tangan.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worklog-dev
resources:
  - template.yaml
images:
  - name: app
    newName: 127.0.0.1:5000/worklog/template
    newTag: "7295d86"
