# Ditulis Jenkins dari deploy/ repo web; jangan diubah tangan.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timesheet-prod
resources:
  - web.yaml
images:
  - name: app
    newName: 127.0.0.1:5000/timesheet/web
    newTag: "dd23b0d"
