# Ditulis Jenkins dari deploy/ repo auth; jangan diubah tangan.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worklog-dev
resources:
  - auth.yaml
images:
  - name: app
    newName: 127.0.0.1:5000/worklog/auth
    newTag: "5721ccd"
